name: Checking

on:
    pull_request:
        branches:
            - master

env:
    PORT: 3000
    PACTUM_REQUEST_BASE_URL: http://127.0.0.1:3000

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: "18"
            - name: install deps
              run: yarn
            - name: run eslint
              run: yarn lint
